version: "3.8"

services:

  meshcentral:
    user: "1000:1000"
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: meshcentral
    restart: unless-stopped
    expose:
      - "80"

    volumes:
      - ./data:/opt/meshcentral/meshcentral-data
      - ./backups:/opt/meshcentral/meshcentral-backups

    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:stable
    container_name: meshcentral-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/meshcentral.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - meshcentral